#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED
#define TAILLE_BLOC     76
#define NB_BLOCS_HAUTEUR    4
#define NB_BLOCS_LARGEUR    7
#define LARGEUR_FENETRE     TAILLE_BLOC*NB_BLOCS_LARGEUR
#define HAUTEUR_FENETRE     TAILLE_BLOC*NB_BLOCS_HAUTEUR
#define TAILLE_BLOC_BIS     5
#define NB_BLOCS_BIS_HAUTEUR    1
#define NB_BLOCS_BIS_LARGEUR    5*TAILLE_BLOC / TAILLE_BLOC_BIS
#define POSITION_VOLUME_Y     3*TAILLE_BLOC + 22
#define POSITION_VOLUME_X     5*TAILLE_BLOC + 10
#define TAILLE_BARRE_VOLUME     80
#define P_BARRE_VOLUME_Y    POSITION_VOLUME_Y + 12
#define P_BARRE_VOLUME_X    POSITION_VOLUME_X + 45
#define MARGE               7



enum{VIDE, PLAY, PAUSE, STOP, FORWARD, BACKWARD, BARRE, NEXT, PLAYED, TOPLAY, TITLE, VOLUME, REPLAY, REPLAY_OFF, REPLAY_ONE, DUREE,
TEMPS_RESTANT, MUTE, MUTE_OFF, BARRE_VOLUME};


#endif // CONSTANTES_H_INCLUDED
